# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Guerra Creativ"
subtitle: "See the world through my eyes!"
author: "JJ Guerrero"
header:
 title: "Photography"
 subtitle: "by JJ Guerrero"
footer:
 name: "Hey there, my name is JJ"
 bio: "It all began by taking pictures of my hobbies. As time went on, my children's activities became my inspiration to capture their moments. I enjoy capturing Sports, Adventure, and Lifestyle shots, but if you are interested in something outside of those, please feel free to email me."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/guerracreativ"
  instagram: "https://www.instagram.com/guerra.creativ"
